export const userRoles = [
  {
    label: "Admin",
    value: 1,
  },
  {
    label: "Giám đốc",
    value: 2,
  },
  {
    label: "Phó Giám đốc",
    value: 3,
  },
  {
    label: "trưởng phòng",
    value: 4,
  },
  {
    label: "Phó phòng",
    value: 5,
  },
  {
    label: "Nhân viên",
    value: 6,
  },
];

export const departments = [
  {
    label: "Hành chính",
    value: 1,
  },
  {
    label: "Kế toán",
    value: 2,
  },
];

export const genders = [
  {
    label: "Nam",
    value: "MALE",
  },
  {
    label: "Nữ",
    value: "FEMALE",
  },
  {
    label: "Không xác định",
    value: "UN_KNOW",
  },
];

export const status = [
  {
    label: "Đang chờ duyệt",
    value: 1,
  },
  {
    label: "Đã duyệt",
    value: 2,
  },
  {
    label: "Hủy",
    value: 3,
  },
];

export const types = [
  {
    label: "ĐN thanh toán",
    value: 1,
  },
  {
    label: "ĐN hợp đồng",
    value: 2,
  },
];

export const contracts = [
  {
    label: "CP VT",
    value: 1,
  },
  {
    label: "CP NC TP",
    value: 2,
  },
  {
    label: "CP Khác",
    value: 2,
  },
];

export const owners = [
  {
    label: "Của tôi",
    value: 1,
  },
  {
    label: "Gửi tới tôi",
    value: 2,
  },
  {
    label: "Tất cả",
    value: 3,
  },
];

export const moneyTypes = [
  {
    label: "VNĐ",
    value: 1,
  },
  {
    label: "USD",
    value: 2,
  },
];

export const thanhToan = [
  {
    label: "CK",
    value: 1,
  },
  {
    label: "Tiền mặt",
    value: 2,
  },
];

export const fakeUsers = [
  {
    label: "Nguyễn Văn A",
    value: 1,
  },
  {
    label: "Nguyễn Văn B",
    value: 2,
  },
  {
    label: "Nguyễn Văn C",
    value: 3,
  },
  {
    label: "Nguyễn Văn D",
    value: 4,
  },
];

export const Nation = [
  { name: "Afghanistan", code: "AF" },
  { name: "land Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Úc", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Đảo Bouvet", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "Lãnh thổ Ấn Độ Dương thuộc Anh", code: "IO" },
  { name: "Bru-nây", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Campuchia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Quần đảo Cayman", code: "KY" },
  { name: "Cộng hòa Trung Phi", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "Trung Quốc", code: "CN" },
  { name: "Đảo Christmas", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Cộng Hòa Dân Chủ Công gô", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: 'Cote D"Ivoire', code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Cộng hòa Séc", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Ai Cập", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "Pháp", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Đức", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "Ấn Độ", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Ý", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Nhật Bản", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Triều Tiên", code: "KP" },
  { name: "Hàn Quốc", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lào", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Hà Lan", code: "NL" },
  { name: "Đảo Antilles của Hà Lan", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Ba Lan", code: "PL" },
  { name: "Bồ Đào Nha", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Liên Bang Nga", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Ả Rập Saudi", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Quần đảo Solomon", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "Nam Phi", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Tây Ban Nha", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Thụy Điển", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Đài Loan", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thái Lan", code: "TH" },
  { name: "Đông-Ti-Mo", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "Các tiểu vương quốc Ả Rập", code: "AE" },
  { name: "Anh", code: "GB" },
  { name: "Mỹ", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Việt Nam", code: "VN" },
  { name: "Quần đảo Virgin thuộc Anh", code: "VG" },
  { name: "Quần đảo Virgin, Hoa Kỳ", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Tây Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export const LAYOUT = {
  labelCol: { span: 4 },
  wrapperCol: { span: 20 },
};
export const TAILLAYOUT = {
  wrapperCol: { offset: 10, span: 16 },
};
export const LAYOUT_FIELD_LONG = {
  labelCol: { span: 6 },
  wrapperCol: { span: 18 },
};

export const LIST_CITY_IN_VN = [
  {
    code: "01",
    name: "Thành phố Hà Nội",
    level: "Thành phố Trung ương",
  },
  {
    code: "02",
    name: "Hà Giang",
    level: "Tỉnh",
  },
  {
    code: "04",
    name: "Cao Bằng",
    level: "Tỉnh",
  },
  {
    code: "06",
    name: "Bắc Kạn",
    level: "Tỉnh",
  },
  {
    code: "08",
    name: "Tuyên Quang",
    level: "Tỉnh",
  },
  {
    code: "10",
    name: "Lào Cai",
    level: "Tỉnh",
  },
  {
    code: "11",
    name: "Điện Biên",
    level: "Tỉnh",
  },
  {
    code: "12",
    name: "Lai Châu",
    level: "Tỉnh",
  },
  {
    code: "14",
    name: "Sơn La",
    level: "Tỉnh",
  },
  {
    code: "15",
    name: "Yên Bái",
    level: "Tỉnh",
  },
  {
    code: "17",
    name: "Hoà Bình",
    level: "Tỉnh",
  },
  {
    code: "19",
    name: "Thái Nguyên",
    level: "Tỉnh",
  },
  {
    code: "20",
    name: "Lạng Sơn",
    level: "Tỉnh",
  },
  {
    code: "22",
    name: "Quảng Ninh",
    level: "Tỉnh",
  },
  {
    code: "24",
    name: "Bắc Giang",
    level: "Tỉnh",
  },
  {
    code: "25",
    name: "Phú Thọ",
    level: "Tỉnh",
  },
  {
    code: "26",
    name: "Vĩnh Phúc",
    level: "Tỉnh",
  },
  {
    code: "27",
    name: "Bắc Ninh",
    level: "Tỉnh",
  },
  {
    code: "30",
    name: "Hải Dương",
    level: "Tỉnh",
  },
  {
    code: "31",
    name: "Hải Phòng",
    level: "Trung ương",
  },
  {
    code: "33",
    name: "Hưng Yên",
    level: "Tỉnh",
  },
  {
    code: "34",
    name: "Thái Bình",
    level: "Tỉnh",
  },
  {
    code: "35",
    name: "Hà Nam",
    level: "Tỉnh",
  },
  {
    code: "36",
    name: "Nam Định",
    level: "Tỉnh",
  },
  {
    code: "37",
    name: "Ninh Bình",
    level: "Tỉnh",
  },
  {
    code: "38",
    name: "Thanh Hóa",
    level: "Tỉnh",
  },
  {
    code: "40",
    name: "Nghệ An",
    level: "Tỉnh",
  },
  {
    code: "42",
    name: "Hà Tĩnh",
    level: "Tỉnh",
  },
  {
    code: "44",
    name: "Quảng Bình",
    level: "Tỉnh",
  },
  {
    code: "45",
    name: "Quảng Trị",
    level: "Tỉnh",
  },
  {
    code: "46",
    name: "Thừa Thiên Huế",
    level: "Tỉnh",
  },
  {
    code: "48",
    name: "Thành phố Đà Nẵng",
    level: "Thành phố Trung ương",
  },
  {
    code: "49",
    name: "Quảng Nam",
    level: "Tỉnh",
  },
  {
    code: "51",
    name: "Quảng Ngãi",
    level: "Tỉnh",
  },
  {
    code: "52",
    name: "Bình Định",
    level: "Tỉnh",
  },
  {
    code: "54",
    name: "Phú Yên",
    level: "Tỉnh",
  },
  {
    code: "56",
    name: "Khánh Hòa",
    level: "Tỉnh",
  },
  {
    code: "58",
    name: "Ninh Thuận",
    level: "Tỉnh",
  },
  {
    code: "60",
    name: "Bình Thuận",
    level: "Tỉnh",
  },
  {
    code: "62",
    name: "Kon Tum",
    level: "Tỉnh",
  },
  {
    code: "64",
    name: "Gia Lai",
    level: "Tỉnh",
  },
  {
    code: "66",
    name: "Đắk Lắk",
    level: "Tỉnh",
  },
  {
    code: "67",
    name: "Đắk Nông",
    level: "Tỉnh",
  },
  {
    code: "68",
    name: "Lâm Đồng",
    level: "Tỉnh",
  },
  {
    code: "70",
    name: "Bình Phước",
    level: "Tỉnh",
  },
  {
    code: "72",
    name: "Tây Ninh",
    level: "Tỉnh",
  },
  {
    code: "74",
    name: "Bình Dương",
    level: "Tỉnh",
  },
  {
    code: "75",
    name: "Đồng Nai",
    level: "Tỉnh",
  },
  {
    code: "77",
    name: "Bà Rịa - Vũng Tàu",
    level: "Tỉnh",
  },
  {
    code: "79",
    name: "Thành phố Hồ Chí Minh",
    level: "Thành phố Trung ương",
  },
  {
    code: "80",
    name: "Long An",
    level: "Tỉnh",
  },
  {
    code: "82",
    name: "Tiền Giang",
    level: "Tỉnh",
  },
  {
    code: "83",
    name: "Bến Tre",
    level: "Tỉnh",
  },
  {
    code: "84",
    name: "Trà Vinh",
    level: "Tỉnh",
  },
  {
    code: "86",
    name: "Vĩnh Long",
    level: "Tỉnh",
  },
  {
    code: "87",
    name: "Đồng Tháp",
    level: "Tỉnh",
  },
  {
    code: "89",
    name: "An Giang",
    level: "Tỉnh",
  },
  {
    code: "91",
    name: "Kiên Giang",
    level: "Tỉnh",
  },
  {
    code: "92",
    name: "Thành phố Cần Thơ",
    level: "Thành phố Trung ương",
  },
  {
    code: "93",
    name: "Hậu Giang",
    level: "Tỉnh",
  },
  {
    code: "94",
    name: "Sóc Trăng",
    level: "Tỉnh",
  },
  {
    code: "95",
    name: "Bạc Liêu",
    level: "Tỉnh",
  },
  {
    code: "96",
    name: "Cà Mau",
    level: "Tỉnh",
  },
];


