export const GET_LIST_CONTRACT_REQUEST = "GET_LIST_CONTRACT_REQUEST";

export const GET_LIST_CONTRACT_REQUEST_SUCCEEDED =
  "GET_LIST_CONTRACT_REQUEST_SUCCEEDED";

export const GET_LIST_CONTRACT_REQUEST_FAILED =
  "GET_LIST_CONTRACT_REQUEST_FAILED";
