export const GET_LIST_EMPLOYEES_REQUEST = "GET_LIST_EMPLOYEES_REQUEST";

export const GET_LIST_EMPLOYEES_REQUEST_SUCCEEDED =
  "GET_LIST_EMPLOYEES_REQUEST_SUCCEEDED";

export const GET_LIST_EMPLOYEES_REQUEST_FAILED =
  "GET_LIST_EMPLOYEES_REQUEST_FAILED";
